services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
      - ./backend/yogadb.db:/app/yogadb.db
    environment:
      ASANAS_IMAGES_DIR: /data/asanas

  frontend:
    build: ./frontend
    ports:
      - "4173:80"
    environment:
      VITE_API_BASE_URL: http://backend:8000/api
    depends_on:
      - backend
